x=10
y=5
tong=x+y
hieu=x-y
tich=x*y
thuong=x/y
print('Tổng của hai số    ', x, '+', y, '=',tong)
print('Hiệu của hai số    ', x, '-', y, '=',hieu)
print('Tích của hai số    ', x, '*', y, '=',tich)
print('Thuong của hai số  ', x, '/', y, '=',thuong)